### PR TITLE
FIX nspdk and refactor code

### PR DESCRIPTION
**Pull request by churnikov**
- [ ] FIX nspdk
- [ ] FIX redundant imports
- [ ] FIX cleanup code
- [ ] UPD using poetry for dependencies

### CODE REVIEW

**Comment by churnikov** [comment]
https://github.com/pyrfume/pyrfume/issues/4

**Comment by rgerkin** [comment]
Using single quotes for strings is going to be a hard habit to break.  I need a new keyboard layout that swaps them! 

- Is PR for tracking or do you want me to merge it now?  
- Did `black` do most of the automatic formatting work here?
- I noticed that many dependency version numbers are now pinned.  I feel like there is usually tradeoff here because it can make it harder to achieve compatibility with other packages that also have pinned dependency versions.   How does poetry handle this?

**Comment by churnikov** [comment]
> Is PR for tracking or do you want me to merge it now?

Yes, I would like to merge it 😄  But you probably should review first. I did fix some obvious bugs. But for me, the most important thing is `smiles_to_nspdk`.

> Did black do most of the automatic formatting work here?

Yes, it was black, including `'` -> `"`.
If you don't like It, there's an option to turn off string conversion `-S, --skip-string-normalization`

> I noticed that many dependency version numbers are now pinned. I feel like there is usually tradeoff here because it can make it harder to achieve compatibility with other packages that also have pinned dependency versions. How does poetry handle this?

1. `lock` doen't affect dependencies in the wheel, It's only useful for local development.
2. Dependencies in `lock` file use semver. If developers that you depend on also use semver then everything will be just fine 
3. From time it's a good habit to check that you can update some dependencies by hand. If you think about it, it's great to have dependencies rely on semver, because then you can be sure that your package will work even years later.

**Review by rgerkin — APPROVED** [review]

**Comment by rgerkin** [comment]
@churnikov Thanks!

**Pull request merged**
